[build]
  publish = "public"
  command = "npm install sass && hugo && sass src/sass/app.scss:static/css/app.css --style compressed"
[context.production.environment]
  HUGO_VERSION = "0.64.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.64.0"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.64.0" 