[build]
  publish = "public"
  command = "npm run build && hugo"
[context.production.environment]
  HUGO_VERSION = "0.64.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.64.0"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.64.0"  

[[redirects]]
  from = "/*"
  to = "https://learn.space-cloud.io/:splat"
  status = 301
  force = true