# This is a basic workflow to help you get started with Actions

name: Learn

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hugo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Check out code into the repository
      uses: actions/checkout@v2      
     
    - name: Compile CSS from SCSS files
      uses: gha-utilities/sass-build@v0.2.2
      with:
        source: src/sass/app.scss
        destination: static/css/app.css

    - name: Build hugo
      uses: srt32/hugo-action@v0.0.3

    - name: Run htmltest to detect errors in html files
      run: curl https://htmltest.wjdp.uk | bash && ./bin/htmltest        